@startuml Domain model
Main -- AlgorithmManager
AlgorithmManager -- "*" Algorithm: contains >
Main -- ApiRequest
Main -- DataManager
DataManager -- DatabaseConnector
DatabaseConnector <|-- LoadData
DatabaseConnector <|-- StoreData



@enduml
