@startuml Domain model

SystemManager -- AlgorithmManager
AlgorithmManager -- "*" Algorithm: contains >
Algorithm -- Recommendation: Generates >
SystemManager -- ApiRequest
SystemManager -- DataManager
DataManager -- DatabaseConnector
DatabaseConnector <|-- StoreData
DatabaseConnector <|-- LoadData
StoreData -- Recommendation: Stores in Database >
SystemManager -- UserManager
UserManager --"*" User
User -- UserSettings
UserManager -- DataManager
User --"*" Algorithm
ApiRequest -- DataManager
@enduml
